# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "ApplicationSetup" ]
  pull_request:
    branches: [ "ApplicationSetup" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
      
    - name: Build with dotnet
      run: dotnet build OnlineCampus/OnlineCampus/OnlineCampus.csproj --configuration Release

    - name: dotnet publish
      run: dotnet publish OnlineCampus/OnlineCampus/OnlineCampus.csproj -c Release -o "${{env.DOTNET_ROOT}}\myotherapp"

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}\myotherapp

  test:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore OnlineCampus/OnlineCampus.sln

      - name: Run tests
        run: dotnet test OnlineCampus/OnlineCampus.Tests/OnlineCampus.Tests.csproj --configuration Release
